<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-E4MMNCGRR6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-E4MMNCGRR6');
</script>

# google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - projects.md
  - profiles.md
  - hackingwhileblind.md

footer: 'follow me on <a href="https://twitter.com/TheBlindHacker">twitter</a>'

style: dark #light # dark (default) or light

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-midnight
#theme: jekyll-theme-console
